# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{miso}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Manfred Stienstra"]
  s.date = %q{2009-10-20}
  s.description = %q{Miso is a unified API for simple image operations commonly used on the web.}
  s.email = %q{manfred@fngtps.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README"
  ]
  s.files = [
    "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "html/classes/Miso.html",
     "html/classes/Miso/Factory.html",
     "html/classes/Miso/Image.html",
     "html/classes/Miso/Processor.html",
     "html/classes/Miso/Processor/CoreImage.html",
     "html/classes/Miso/Processor/ImageMagick.html",
     "html/classes/Miso/Processor/NotImplementedError.html",
     "html/created.rid",
     "html/files/LICENSE.html",
     "html/files/README.html",
     "html/files/lib/miso/factory_rb.html",
     "html/files/lib/miso/image_rb.html",
     "html/files/lib/miso/processor/core_image_rb.html",
     "html/files/lib/miso/processor/image_magick_rb.html",
     "html/files/lib/miso/processor_rb.html",
     "html/files/lib/miso_rb.html",
     "html/fr_class_index.html",
     "html/fr_file_index.html",
     "html/fr_method_index.html",
     "html/index.html",
     "html/rdoc-style.css",
     "lib/miso.rb",
     "lib/miso/factory.rb",
     "lib/miso/image.rb",
     "lib/miso/processor.rb",
     "lib/miso/processor/core_image.rb",
     "lib/miso/processor/image_magick.rb",
     "spec/api/factory_spec.rb",
     "spec/api/image_spec.rb",
     "spec/api/processor/image_magick_spec.rb",
     "spec/api/processor_spec.rb",
     "spec/fixtures/120x100.png",
     "spec/start.rb"
  ]
  s.homepage = %q{http://github.com/Fingertips/miso}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Miso is a unified API for simple image operations commonly used on the web.}
  s.test_files = [
    "spec/api/factory_spec.rb",
     "spec/api/image_spec.rb",
     "spec/api/processor/image_magick_spec.rb",
     "spec/api/processor_spec.rb",
     "spec/start.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
